version: "3.8"

services:
  blockchain:
    build: ./blockchain
    container_name: voting-blockchain
    ports:
      - "8545:8545"
    volumes:
      - shared-data:/app/deployments

  backend:
    build: ./backend
    container_name: voting-backend
    ports:
      - "5000:5000"
    volumes:
      - shared-data:/app/deployments:ro
    depends_on:
      - blockchain

  frontend:
    build: ./frontend
    container_name: voting-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - WDS_SOCKET_PORT=0
    depends_on:
      - backend
    stdin_open: true

volumes:
  shared-data:

